### ISSUE TITLE
OMF New Feature Set

### ISSUE THREAD

**Issue by bucaran** [bucaran/fishline#583]
+ [ ] Improve directory structure. #580
+ [ ] Rewrite install script in `fish`#581
+ [ ] Deprecate OMF_SKIP #588 
+ [ ] Allow plugins to extend the CLI via event emitters

#### Other Goodies

+ [ ] Core should provide a plumbing API (most of these functions are already defined in core) so that plugins can extend `omf` with custom commands. 

+ We used to talk about plugins _and_ themes, but now we are saying these in fact are the same thing. In an even broader sense, not only they are the same, but even a simple directory exposing a `functions/` or `completions/` directory ***is*** a package. So, what I propose is that we move from the idea of plugins, themes and other inconsistencies to the unified idea of "packages" where a package is basically a directory inside `pkg/` that can do any or more of the following:

  * [ ] Expose a global function (known as plugin until now)
  * [ ] Observe an init_<package name> event/signal
  * [ ] Expose a functions/ directory loaded into $fish_function_path
  * [ ] Expose a completions/ directory loaded into $fish_complete_path
  * [ ] Define fish prompt functions (`fish_prompt.fish`, etc.)
